### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by dhooper** [hashrocket/mousetrap#1]
I've noticed, while playing with Mousetrap in script/console, that once an API call results in an "Authentication required" error from Cheddargetter there is no way to re-authenticate after that point for the rest of my console session.

I'm also unable to get the smoke test to run -- every step results in "Authentication required" errors. My credentials are stored in settings.yml as directed.

Might these two issues be related? Have you heard of this happening before? I'm using Rails 2.3.4 with REE 1.8.7, if it makes any difference.

**Comment by l4rk** [comment]
Thanks for reporting your findings! Will look into your re-authenticate issue. As for the smoke test, I've found that you have to have httparty 0.4.2 and _only_ that version installed, or it will fail. I'm going to ask the maintainer of httparty what I can do about that. That'll be easy, since he's my roommate. ;) Thanks again, man.

**Comment by jwworth** [comment]
Closing this issue; Mousetrap has been superseded by the official client: https://github.com/expectedbehavior/cheddargetter_client_ruby.
